from google.appengine.ext import ndb


''' The BlogModel is a google datastore model. The entity keys are not manually set and will be
	automatically generated by the datastore.
	
	DATE_CREATED  is manually set, but the date edited is automatically updated for every put.
	
'''
class BlogModel(ndb.Model):
	title = ndb.StringProperty(required=True)
	entry = ndb.TextProperty(required=True)
	date_created = ndb.DateTimeProperty(auto_now_add=False,  auto_now=False)
	date_edited = ndb.DateTimeProperty(auto_now_add=True,  auto_now=False)
	



